-- database: :memory:
-- SQLite
CREATE TABLE IF NOT EXISTS LOGIN (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,
    LOGIN_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);