-- database: :memory:
-- SQLite
CREATE TABLE IF NOT EXISTS books (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    quantity INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS LOGIN (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,
    LOGIN_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- is this a comment?
-- this is a comment